### ISSUE TITLE
Show example in body

### ISSUE THREAD

**Issue by bertramakers** [luckymarmot/Paw-SwaggerImporter#21]
I'm not sure if I'm missing something, but whenever I import a Swagger file none of the requests have any information about the body. (For POST/PUT/PATCH requests.)

Using the Pet Store definition on Swagger UI as an example,  you can see that they can show an example body which helps when filling out the request. However importing the corresponding Swagger file in Paw using this extension results in empty body fields.

Would it be possible to implement body field examples like Swagger UI does? You could directly put them in the body field, and they'd be a great help as starting templates IMHO.

**Comment by mittsh** [comment]
@bertramakers We're working on a large project to handle API description formats ([API Flow](https://github.com/luckymarmot/API-Flow)), and it will handle body nicely, and even generate random data using JSON schema faker. I think it will help in your case.

**Comment by bertramakers** [comment]
Sounds good! Is this something we can already try out, or is it far from ready?

**Comment by mittsh** [comment]
@bertramakers it's not so far…but we still need to adapt stuff to make it available to use in Paw (cc @JonathanMontane)

**Comment by bertramakers** [comment]
Ok great, looking forward to testing it whenever it's usable in Paw. I'll keep an eye out for it.

**Comment by JonathanMontane** [comment]
fixed in v2.2.0

**Comment by bertramakers** [comment]
Not sure if it's me doing something wrong, or something you overlooked, but most of our endpoints in Swagger use references to describe their parameters. But instead of looking up those references, the reference name gets injected into the request body. See attached screenshot.

![screen shot 2016-08-30 at 10 17 56](https://cloud.githubusercontent.com/assets/959026/18081553/25430618-6e9b-11e6-8466-3067e8deb5a6.png)

**Comment by JonathanMontane** [comment]
@bertramakers, from version 2.2 onwards, the definitions that are present in the swagger file are stored in an environment domain, and should use the JSON Schema Faker dynamic value (or JSF). The JSF dynamic value is something we're really stoked about, because it allows you to generate fake data that complies with the schema.

So what you are actually seeing here is actually a reference to an environment variable, named `#/definitions/OrganizerCreate`, that you should be able to find in the environment domain named `swagger`, which should be the name of the file you imported.

Under normal circumstances, the environment variable should contain a JSF dynamic value. Unfortunately, there is currently an ongoing issue with importer settings not being taken into account in Paw, that will make your definitions empty instead. This should be fixed with the next release of Paw (that should come out tomorrow).

If you need to have this feature as soon as possible, you can always shoot an e-mail to support, and I'll gladly import the file in a local paw document for you.

An intermediate solution is to copy paste the JSON Schemas that interest you in JSF dynamic values in the environments, but this is going to be a pain if you have more than a few schemas that interest you.

![image](https://cloud.githubusercontent.com/assets/5136989/18082716/5f44525e-6ea0-11e6-9cff-80f67bcda54e.png)

I apologize for the inconvenience

**Comment by bertramakers** [comment]
That's fine, I'll just wait for the next release. Thanks for the fast reply! :)
