### ISSUE TITLE
Does not correctly handle multiple "schemes" values

### ISSUE THREAD

**Issue by lumaxis** [luckymarmot/Paw-SwaggerImporter#25]
The OpenAPI spec allows for the `schemes:` property to be an array of strings, see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema

If a Swagger file includes something like this

``` yaml
schemes:
  - https
  - http
```

the importer apparently ignores both values and shows this instead:
![screenshot 2016-08-25 02 38 04](https://cloud.githubusercontent.com/assets/406937/17952663/f85b7a86-6a6c-11e6-9cf1-5d5205e31093.png)

**Comment by JonathanMontane** [comment]
Thanks for the report, I'll look into it!

**Comment by JonathanMontane** [comment]
@lumaxis Found the bug, working on a fix right now (your two issues are linked and are part of a much wider issue)

**Comment by lumaxis** [comment]
I had a feeling this might be the case. Thanks for looking into it and working on a fix!

**Comment by lumaxis** [comment]
@JonathanMontane Should this already be fixed by 3.0.9? I noticed things changed a little but the current behavior is still a bit strange.
I think the `schemes` values now get imported using JSF enums but this is not very practical imo. The way it works now, the actually used protocol becomes random and unpredictable whereas I would love to have this become a globally changeable environment variable.
Same goes for the `host:` parameter btw. I would love to have a way to easily change the host used for all requests 😊

Thad said, thanks for the work you're doing on this! Great to see the progress and fixes. ❤

**Comment by JonathanMontane** [comment]
@lumaxis Sorry about that! The issue was internal to Paw and got fixed in Paw 3.0.9. However, what you are describing was also fixed in a joint release. Try updating your extensions, you should now have two additional options for the random generation on imports, specifically for the protocol and host (we were also annoyed by it). In theory, these two checkboxes should be disabled by default, so you won't have to do anything to fix this issue, apart from updating.

If you still encounter any other issue,  feel free to open up an issue or create a ticket with support!

**Comment by lumaxis** [comment]
Hah, you're indeed right :) When I had tried last night, the Swagger Importer update hadn't reached me yet, now it's looking exactly like you describe.
